name: DevSecOps CI Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch: # This adds a manual "Run workflow" button to the UI!

env:
  DOCKER_IMAGE: secure-app
  REGISTRY_NAME: docker.io

jobs:
  devsecops-delivery:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Repository Source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Gate 1: Code Linting & Unit Testing Mock Verification
    - name: Execute Code Linting & Verification
      run: |
        echo "Running structural syntax checks..."
        echo "Running application unit testing sequences..."
        echo "Source code state verified successfully!"

    # Gate 2: Static Application Security Testing (SAST)
    - name: Run Official SonarQube Analysis Scan
      uses: sonarsource/sonarqube-scan-action@v3
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        args: -Dsonar.projectKey=high-velocity-pipeline -Dsonar.sources=.

    # Gate 3: Package, Containerize, and Scan Image Layers
    - name: Build Code Container Runtime Layers
      run: docker build -t $REGISTRY_NAME/$DOCKER_IMAGE:${{ github.sha }} .

    - name: Run Trivy Vulnerability Scan Inspector
      uses: aquasecurity/trivy-action@v0.36.0
      with:
        image-ref: 'docker.io/secure-app:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL'
